[profile.default]
src = "backend"
test = "backend"
out = "out"
libs = []
solc = "0.8.37"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./" }]
gas_reports = ["HoroiRegistry"]
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]

[rpc_endpoints]
bsc = "https://bsc-dataseed.bnbchain.org"

[fuzz]
runs = 256
