export const ErrorCodes = {
  INPUT_INVALID: "INPUT_INVALID",
  ADDRESS_INVALID: "ADDRESS_INVALID",
  CHAIN_MISMATCH: "CHAIN_MISMATCH",
  RPC_UNAVAILABLE: "RPC_UNAVAILABLE",
  RPC_RATE_LIMITED: "RPC_RATE_LIMITED",
  RUN_BUSY: "RUN_BUSY",
  BLOCK_NOT_FOUND: "BLOCK_NOT_FOUND",
  ASSET_NOT_CONTRACT: "ASSET_NOT_CONTRACT",
  CORE_INTERFACE_MISSING: "CORE_INTERFACE_MISSING",
  PENDING_INTERFACE_MISSING: "PENDING_INTERFACE_MISSING",
  OPTIONAL_INTERFACE_UNAVAILABLE: "OPTIONAL_INTERFACE_UNAVAILABLE",
  MULTIPLIER_INVALID: "MULTIPLIER_INVALID",
  PENDING_STATE_INVALID: "PENDING_STATE_INVALID",
  TARGET_UNSUPPORTED: "TARGET_UNSUPPORTED",
  ADAPTER_INVALID: "ADAPTER_INVALID",
  DEPOSIT_FAILED: "DEPOSIT_FAILED",
  REDEEM_FAILED: "REDEEM_FAILED",
  FORK_START_FAILED: "FORK_START_FAILED",
  FORK_MUTATION_UNAVAILABLE: "FORK_MUTATION_UNAVAILABLE",
  FORK_TRANSACTION_FAILED: "FORK_TRANSACTION_FAILED",
  INVARIANT_VALUE_NOT_CONSERVED: "INVARIANT_VALUE_NOT_CONSERVED",
  INVARIANT_MULTIPLIER_IGNORED: "INVARIANT_MULTIPLIER_IGNORED",
  INVARIANT_MULTIPLIER_DOUBLE_APPLIED: "INVARIANT_MULTIPLIER_DOUBLE_APPLIED",
  INVARIANT_APPLIED_EARLY: "INVARIANT_APPLIED_EARLY",
  INVARIANT_APPLIED_LATE: "INVARIANT_APPLIED_LATE",
  INVARIANT_REDEMPTION_DRIFT: "INVARIANT_REDEMPTION_DRIFT",
  INVARIANT_ROUNDING_EXCEEDED: "INVARIANT_ROUNDING_EXCEEDED",
  INVARIANT_EVENT_MISMATCH: "INVARIANT_EVENT_MISMATCH",
  REPORT_HASH_FAILED: "REPORT_HASH_FAILED",
  CONTEXT_HASH_FAILED: "CONTEXT_HASH_FAILED",
  BINANCE_API_NOT_CONFIGURED: "BINANCE_API_NOT_CONFIGURED",
  BINANCE_AUTH_FAILED: "BINANCE_AUTH_FAILED",
  BINANCE_SIGNATURE_MISMATCH: "BINANCE_SIGNATURE_MISMATCH",
  BINANCE_TIMESTAMP_DRIFT: "BINANCE_TIMESTAMP_DRIFT",
  BINANCE_RATE_LIMITED: "BINANCE_RATE_LIMITED",
  BINANCE_UPSTREAM_UNAVAILABLE: "BINANCE_UPSTREAM_UNAVAILABLE",
  BINANCE_RESPONSE_INVALID: "BINANCE_RESPONSE_INVALID",
  RWA_ASSET_NOT_FOUND: "RWA_ASSET_NOT_FOUND",
  RWA_PLATFORM_UNSUPPORTED: "RWA_PLATFORM_UNSUPPORTED",
  RWA_CONTEXT_STALE: "RWA_CONTEXT_STALE",
  RWA_REFERENCE_UNAVAILABLE: "RWA_REFERENCE_UNAVAILABLE",
  TX_SIMULATION_FAILED: "TX_SIMULATION_FAILED",
  TX_PAYLOAD_CHANGED_AFTER_SIMULATION: "TX_PAYLOAD_CHANGED_AFTER_SIMULATION",
  REGISTRY_NOT_CONFIGURED: "REGISTRY_NOT_CONFIGURED",
  REGISTRY_ALREADY_PUBLISHED: "REGISTRY_ALREADY_PUBLISHED",
  REGISTRY_TX_REVERTED: "REGISTRY_TX_REVERTED",
  REGISTRY_READBACK_FAILED: "REGISTRY_READBACK_FAILED",
  WALLET_READBACK_FAILED: "WALLET_READBACK_FAILED",
  PUBLICATION_MISMATCH: "PUBLICATION_MISMATCH",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const httpStatusFor = (code: ErrorCode): number => {
  switch (code) {
    case ErrorCodes.INPUT_INVALID:
    case ErrorCodes.ADDRESS_INVALID:
    case ErrorCodes.CHAIN_MISMATCH:
    case ErrorCodes.ADAPTER_INVALID:
    case ErrorCodes.TARGET_UNSUPPORTED:
      return 400;
    case ErrorCodes.BLOCK_NOT_FOUND:
      return 404;
    case ErrorCodes.REGISTRY_ALREADY_PUBLISHED:
      return 409;
    case ErrorCodes.CORE_INTERFACE_MISSING:
    case ErrorCodes.PENDING_INTERFACE_MISSING:
    case ErrorCodes.ASSET_NOT_CONTRACT:
    case ErrorCodes.MULTIPLIER_INVALID:
    case ErrorCodes.PENDING_STATE_INVALID:
    case ErrorCodes.FORK_MUTATION_UNAVAILABLE:
      return 422;
    case ErrorCodes.RPC_RATE_LIMITED:
    case ErrorCodes.RUN_BUSY:
      return 429;
    case ErrorCodes.BINANCE_API_NOT_CONFIGURED:
    case ErrorCodes.RWA_ASSET_NOT_FOUND:
    case ErrorCodes.RWA_PLATFORM_UNSUPPORTED:
    case ErrorCodes.RWA_REFERENCE_UNAVAILABLE:
    case ErrorCodes.TX_SIMULATION_FAILED:
    case ErrorCodes.WALLET_READBACK_FAILED:
      return 424;
    case ErrorCodes.RPC_UNAVAILABLE:
    case ErrorCodes.BINANCE_AUTH_FAILED:
    case ErrorCodes.BINANCE_SIGNATURE_MISMATCH:
    case ErrorCodes.BINANCE_TIMESTAMP_DRIFT:
      return 502;
    case ErrorCodes.BINANCE_RATE_LIMITED:
      return 429;
    case ErrorCodes.BINANCE_UPSTREAM_UNAVAILABLE:
    case ErrorCodes.BINANCE_RESPONSE_INVALID:
      return 502;
    case ErrorCodes.PUBLICATION_MISMATCH:
      return 409;
    default:
      return 500;
  }
};

export class HoroiError extends Error {
  readonly code: ErrorCode;
  readonly details?: unknown;

  constructor(code: ErrorCode, message?: string, details?: unknown) {
    super(message ?? code);
    this.name = "HoroiError";
    this.code = code;
    this.details = details;
  }
}
